name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    container:
      image: kalilinux/kali-rolling
      options: --privileged  # live-build needs privileges

    steps:
      - name: Install GitHub Actions dependencies (core packages)
        run: |
          apt update
          apt install -y sudo curl gnupg ca-certificates

      - name: Add sudo user workaround for container
        run: |
          echo 'github ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          apt update
          apt install -y git simple-cdd cdebootstrap p7zip wget  live-build
          pipx install GofileIOUploader

      - name: Build ISO image
        run: |
          ./build.sh --verbose --variant minimal
        continue-on-error: true

      - name: Upload build log even on failure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: ./build.log

      - name: Upload image and log to gofile.io
        id: gofile
        if: success()
        run: |
          gofile-upload --save image.csv --public images/
          echo "name=$(cut -d',' -f10 image.csv)" >> "$GITHUB_OUTPUT"
          echo "url=$(cut -d',' -f16 image.csv)" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release with IA URL
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          body: [${{ steps.gofile.outputs.name }}](${{ steps.gofile.outputs.url }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
