name: Sync from GitLab main branch

on:
  schedule:
    - cron: '0 0 * * *' # runs everyday
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://gitlab.com/kalilinux/build-scripts/kali-live.git
          git fetch gitlab main

      - name: Rebase GitHub main on GitLab main
        run: |
          git rebase gitlab/main

      - name: Push rebased changes to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git push --force-with-lease origin main
